name: task_time
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Adjusted to a common recent range, spec mentioned 3.22.0 for Flutter / Dart 3.4.0

dependencies:
  flutter:
    sdk: flutter

  # State Management (Riverpod)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.0.0

  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

  # Permissions
  permission_handler: ^11.3.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI/UX Helpers
  intl: ^0.19.0 # For date/time formatting
  # flutter_slidable: ^3.1.0 # Add later when needed for task list
  # flutter_xlider: ^3.4.0 # Add later when needed for task form
  # reorderable_list: ^0.0.4 # Add later for Eisenhower Matrix

  # Timezone
  timezone: ^0.9.2

  # Device Apps (for listing installed apps)
  device_apps: ^2.2.0

  # UUID generation
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.5
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
